// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/mytheresa/go-hiring-challenge/models"
)

// MockCatalogService is a mock of CatalogService interface.
type MockCatalogService struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceMockRecorder
}

// MockCatalogServiceMockRecorder is the mock recorder for MockCatalogService.
type MockCatalogServiceMockRecorder struct {
	mock *MockCatalogService
}

// NewMockCatalogService creates a new mock instance.
func NewMockCatalogService(ctrl *gomock.Controller) *MockCatalogService {
	mock := &MockCatalogService{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogService) EXPECT() *MockCatalogServiceMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCatalogService) CreateCategory(ctx context.Context, Category *models.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, Category)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCatalogServiceMockRecorder) CreateCategory(ctx, Category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCatalogService)(nil).CreateCategory), ctx, Category)
}

// GetAllCategories mocks base method.
func (m *MockCatalogService) GetAllCategories(ctx context.Context) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories", ctx)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockCatalogServiceMockRecorder) GetAllCategories(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockCatalogService)(nil).GetAllCategories), ctx)
}

// GetAllProducts mocks base method.
func (m *MockCatalogService) GetAllProducts(ctx context.Context, filters *models.ProductFilter) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", ctx, filters)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockCatalogServiceMockRecorder) GetAllProducts(ctx, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockCatalogService)(nil).GetAllProducts), ctx, filters)
}

// GetProductDetails mocks base method.
func (m *MockCatalogService) GetProductDetails(ctx context.Context, ProductCode string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductDetails", ctx, ProductCode)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductDetails indicates an expected call of GetProductDetails.
func (mr *MockCatalogServiceMockRecorder) GetProductDetails(ctx, ProductCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductDetails", reflect.TypeOf((*MockCatalogService)(nil).GetProductDetails), ctx, ProductCode)
}
